### ISSUE TITLE
Exporting and then opening a .grist file doesn't work correctly

### ISSUE THREAD

**Issue by ruudschouten** [gristlabs/grist-desktop#4] opened 2023-04-07 12:03 UTC
Currently on version 0.2.1, and wanted to export a newly created document.

Exporting is done by opening the document, clicking `Share` > `Download`.

If I then try to import this exported .grist file, I get a warning popup which says:

> Import failed: File format is not supported.

If I instead double click the .grist file to open Grist automatically with this file, I get a different error:

> **Error accessing document**
> You can try reloading the document, or using recovery mode. Recovery mode opens the document to be fully accessible to owners, and inaccessible to others. It also disables formulas. [SQLITE_CANTOPEN: unable to open database file]

Trying to enter recovery mode will show a toast message in the lower left stating

>14:01:20 SQLITE_CANTOPEN: unable to open database file.

This also has a nice Report button, but when I click this I get another toast message, saying the report form isn't set up.

**Comment by paulfitz** [comment] 2023-04-07 13:03
Thanks for reporting this @ruudschouten, will look into it. Which OS was this? In the meantime, you should be able to find Grist documents sitting on your filesystem as `.grist` files.

**Comment by ruudschouten** [comment] 2023-04-07 13:26
This was on Windows 10; Version 10.0.19045 Build 19045

**Comment by nasmi3** [comment] 2023-04-12 07:32
Hi,
I saw the same issue on windows. Grist is able to open any `.grist` file created by making a new doc through the app. However it doesn't work when :
- I make a copy of the `.grist` file, rename it and try to open it
- Try to open a `.grist` file created and downloaded a server instance of grist (grist-core)

It might be linked with the fact that the documents have colliding or absent document id in the sqlite (like the home.sqlite for grist-core)

**Comment by nasmi3** [comment] 2023-04-12 23:30
Dear Paul,
Yes, I am on windows 10 too. I haven't checked on other platforms.
Again thank you for your work on this project !

Le mer. 12 avr. 2023 à 23:57, Paul Fitzpatrick ***@***.***> a
écrit :

**Comment by ianzhuo** [comment] 2023-04-13 06:55
> Hi, I saw the same issue on windows. Grist is able to open any `.grist` file created by making a new doc through the app. However it doesn't work when :
> 
> * I make a copy of the `.grist` file, rename it and try to open it
> * Try to open a `.grist` file created and downloaded a server instance of grist (grist-core)
> 
> It might be linked with the fact that the documents have colliding or absent document id in the sqlite (like the home.sqlite for grist-core)

Hi, I  I tried to roll back to grist-electron-windows-0.1.8-x64.exe, and then the file opening function back to normal.

**Comment by Anamon** [comment] 2023-11-12 21:33
This persists in version 1.1.3.

There seems to be some internal (to the `.grist` file) or external source which keeps a record of a `.grist` files absolute path and filename. It needs to stay absolutely the same, otherwise it can't be opened anymore.

**Reproduction steps**
1. Create a new file in the app, note the location of the `.grist` file in the user's directory.
2. Close grist-electron.
3. Change some letter in the filename of the `.grist` file.
4. Open the `.grist` file in grist-electron.
5. Close grist-electron.
6. Change the name of the `.grist` file back to the original name.
7. Open the `.grist` file again in grist-electron.

In step 4, you will get the `SQLITE_CANTOPEN` error when trying to open the file. In step 7, after restoring the original filename, the file opens properly again. So there is obviously nothing wrong with the file itself (other applications can also open it as an SQLite3 file without issues).

**Comment by paulfitz** [comment] 2023-11-13 13:46
Hi @Anamon, the interaction between the Electron version of Grist and the file system is super primitive:
https://github.com/gristlabs/grist-electron/blob/04a8fc54d22d8d571d97bddcc1545c0fe40f5c59/ext/app/electron/main.ts#L188-L200
Basically, it is using a simple hack to adapt the server version of Grist (which has full control of where files are stored) to the desktop. The server version expects to have a little entry for each file in a database, so we make one to keep it happy. This could definitely be improved!

**Comment by jyio** [comment] 2024-02-11 16:24
Greetings. Grist serves me just fine in headless mode, but I got curious about the desktop distribution. I'm seeing similar behavior in release 0.2.8 on Windows 10 when attempting to open a `*.grist` file from the filesystem,

> **Error accessing document**
> You can try reloading the document, or using recovery mode. Recovery mode opens the document to be fully accessible to owners, and inaccessible to others. It also disables formulas. [SQLITE_CANTOPEN: unable to open database file]

It could *import* the very same file just fine, but of course that results in a new file in `%USERPROFILE%\Documents`. Now, this file could be opened without error, but a *different* file copied into `%USERPROFILE%\Documents` triggers `SQLITE_CANTOPEN`.

**Comment by tbleiker** [comment] 2024-06-20 15:06
Same here with 0.2.9 on Windows 10 and Windows 11. I cannot download a grist project to another folder and open it (`SQLITE_CANTOPEN: unable to open database file`).

**Comment by paulfitz** [comment] 2024-06-20 19:46
@SleepyLeslie do you have any insight into what @tbleiker is seeing? I know we plan to make big changes to how Desktop interacts with the file system to make it more "normal", but even under the limited current adapter I'd have thought opening a Grist file in a folder should work.

**Comment by SleepyLeslie** [comment] 2024-06-24 15:33
Confirmed on Windows (only). The issue is with `fse.symlink`, where Grist Desktop mistakenly specifies the `type` as "junction". Windows junctions do not require special privileges, but can only work for directories, not files. This could be simply fixed by removing the `type` parameter and let Node.js infer it (will result in "file" which is correct). However, this won't fix the user experience since Windows requires users to have a special privilege (`Local Policies\User Rights Assignment\Create symbolic links`) to create symlinks, and we'll just begin to hit permission errors instead.

A plausible workaround is to use shortcuts instead of symlinks. If this is confirmed to work, I'll squeeze the fix into the next release.

**Comment by SleepyLeslie** [comment] 2024-06-24 15:57
Another plausible ad-hoc fix is to tell users to explicitly grant the "Create symbolic links" permission to themselves, but this has some security implications: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766301(v=ws.10)?redirectedfrom=MSDN#create-symbolic-links

**Closed** 2024-06-25 20:07 UTC
Labels: bug

**Comment by tbleiker** [comment] 2025-04-22 11:19
Any Upate on this?

**Comment by tbleiker** [comment] 2025-04-22 15:04
I have updated to the latest version and it's working now! Sorry for any confusion. It's hard to keep track of all the possible updates in Windows 😅
